### ISSUE TITLE
I'm having a problem

### ISSUE THREAD

**Issue by jjtnb123** [opparco/io_anim_hkx#10]
Traceback (most recent call last):
  File "C:\Users\jintai\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_anim_hkx\hka_import_op.py", line 46, in execute
    import_hkafile(skeleton_file, anim_bin_file, use_anim)
  File "C:\Users\jintai\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_anim_hkx\hka_import.py", line 241, in import_hkafile
    anim.load(anim_file)
  File "C:\Users\jintai\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_anim_hkx\io\hka.py", line 274, in load
    self.load_stream(file)
  File "C:\Users\jintai\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_anim_hkx\io\hka.py", line 282, in load_stream
    nskeletons = read_int(file)
  File "C:\Users\jintai\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_anim_hkx\io\hka.py", line 37, in read_int
    return unpack('<i', file.read(4))[0]
struct.error: unpack requires a bytes object of length 4

location: <unknown location>:-1

**Comment by jjtnb123** [comment]
Animations don't work

**Comment by jjtnb123** [comment]
only have skeleton
